server:
  port: 8080

spring:
  application:
    name: nacos-provider

  cloud:
    nacos:
      discovery:
        # nacos 服务地址 IP:PORT
        server-addr: 192.168.242.129:8848

management:
  endpoint:
    web:
      exposure:
        include: "*"
