server:
  port: 9080

spring:
  application:
    name: cloud-nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.242.129:8848

# 消费者要访问的服务提供者（注册成功的Nacos的微服务提供者）
service-url:
  nacos-provider-service: http://cloud-nacos-provider
