server:
  port: 8003

spring:
  application:
    name: order-service

  cloud:
    nacos:
      discovery:
        # Nacos 集群配置
        server-addr: 192.168.242.112:81

management:
  endpoints:
    web:
      exposure:
        include: '*'
