server:
  port: 7071

spring:
  application:
    name: cloud-nacos-config

  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 192.168.242.112:81
  config:
    import:
      - nacos:test.yml




