server:
  port: 7072

spring:
  application:
    name: sentinel-service

  cloud:
    nacos:
      discovery:
        # Nacos 集群
        server-addr: 192.168.242.112:81
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      # https://github.com/alibaba/Sentinel/issues/1213 链路规则问题
      web-context-unify: false
      # Sentinel 规则持久化到 Nacos
      datasource:
        rule1:
          nacos:
            serverAddr: 192.168.242.112:81
            groupId: DEFAULT_GROUP
            dataId: sentinelFlowRule.json
            ruleType: flow
        rule2:
          nacos:
            serverAddr: 192.168.242.112:81
            groupId: DEFAULT_GROUP
            dataId: hotKeyRule.json
            ruleType: param-flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

