server:
  port: 7071

spring:
  application:
    name: nacos-config

  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 192.168.242.129:8848
  config:
    import:
      - nacos:test.yml
